### ISSUE TITLE
How to get the currently logged on Windows user from within a Go program?

### ISSUE THREAD

**Issue by m4mark** [lextudio/httpbridge#4]
I've installed the latest release and am now trying to access the LOGON_USER header in a Go program, but having no success, what needs to be configured for me to do this? It feels like I'm missing something.

See my Web.config file below.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<system.webServer>
		<handlers>
			<add name="httpPlatformHandler" path="*" verb="*" modules="httpPlatformHandler" resourceType="Unspecified" requireAccess="Script" />
		</handlers>
		<httpPlatform startupTimeLimit="20" processPath="C:\Some\Location\server.exe" arguments="--port %HTTP_PLATFORM_PORT%" forwardWindowsAuthToken="true">
		</httpPlatform>
	</system.webServer>
</configuration>
```

Many thanks.

**Comment by m4mark** [comment]
I'm adding this excerpt from my Web.config file, not certain why is does not appear in original message.

httpPlatform startupTimeLimit="20" processPath="C:\Some\Location\server.exe" arguments="--port %HTTP_PLATFORM_PORT%" forwardWindowsAuthToken="true"

**Comment by lextm** [comment]
There is no `LOGON_USER` header. You need to

* Upgraded to RC3.
* Use `X-IIS-WindowsAuthToken` header to get the token and then extract the user name.

**Comment by m4mark** [comment]
Thank you for the update.

I've installed RC3 and the new header is not appearing, below are all the request headers my Go program can see.

- Accept
- Accept-Encoding
- Accept-Language
- Cache-Control
- Connection
- Host
- Ms-Aspnetcore-Token
- Pragma
- Upgrade-Insecure-Requests
- User-Agent
- X-Forwarded-For
- X-Forwarded-Proto

**Comment by lextm** [comment]
You have to enable Windows authentication and anonymous authentication must be disabled.

**Comment by m4mark** [comment]
Cool, disabling anonymous auth worked a treat, many thanks.

**Comment by joshkay** [comment]
How do you extract the user name from `X-IIS-WindowsAuthToken`

**Comment by lextm** [comment]
@joshkay You might want to check out https://docs.lextudio.com/blog/httpplatformhandler-windows-authentication-tips/

**Comment by joshkay** [comment]
> @joshkay You might want to check out https://docs.lextudio.com/blog/httpplatformhandler-windows-authentication-tips/

Awesome article and perfect timing thanks!  Unfortunately trying to get this to work in a node app, so will try to investigate further based on what you have found.
